spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5452/hasta
    username: kbs
    password: kbs
    driverClassName: org.postgresql.Driver